11-23 22:38:06 [SUCCESS] nonebot | NoneBot is initializing...
11-23 22:38:06 [INFO] nonebot | Current Env: dev
11-23 22:38:06 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 53245, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {''}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'fastapi_reload': True}
11-23 22:38:06 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
11-23 22:38:06 [SUCCESS] nonebot | Succeeded to import "echo"
11-23 22:38:06 [ERROR] nonebot | Failed to import ""
Traceback (most recent call last):
  File "/root/bot/bot-centos/nbbot/bot.py", line 34, in <module>
    nonebot.load_all_plugins([""],["src/plugins"])
  File "/usr/local/lib/python3.10/site-packages/nonebot/plugin/load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1047, in _gcd_import
  File "<frozen importlib._bootstrap>", line 981, in _sanity_check
ValueError: Empty module name
11-23 22:38:06 [SUCCESS] nonebot | Succeeded to import "test_plugin"
11-23 22:38:06 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
11-23 22:38:06 [SUCCESS] nonebot | Running NoneBot...
11-23 22:38:06 [DEBUG] nonebot | Loaded adapters: OneBot V11
11-23 22:38:06 [INFO] uvicorn | Will watch for changes in these directories: ['/root/bot/bot-centos/nbbot']
11-23 22:38:06 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:53245 (Press CTRL+C to quit)
11-23 22:38:06 [INFO] uvicorn | Started reloader process [30501] using WatchFiles
11-23 22:38:07 [SUCCESS] nonebot | NoneBot is initializing...
11-23 22:38:07 [INFO] nonebot | Current Env: dev
11-23 22:38:07 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 53245, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {''}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'fastapi_reload': True}
11-23 22:38:07 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
11-23 22:38:07 [SUCCESS] nonebot | Succeeded to import "echo"
11-23 22:38:07 [ERROR] nonebot | Failed to import ""
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/local/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/local/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/local/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/local/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/bot/bot-centos/nbbot/bot.py", line 34, in <module>
    nonebot.load_all_plugins([""],["src/plugins"])
  File "/usr/local/lib/python3.10/site-packages/nonebot/plugin/load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1047, in _gcd_import
  File "<frozen importlib._bootstrap>", line 981, in _sanity_check
ValueError: Empty module name
11-23 22:38:07 [SUCCESS] nonebot | Succeeded to import "test_plugin"
11-23 22:38:07 [INFO] uvicorn | Started server process [30505]
11-23 22:38:07 [INFO] uvicorn | Waiting for application startup.
11-23 22:38:07 [INFO] uvicorn | Application startup complete.
11-23 22:38:08 [INFO] uvicorn | ('127.0.0.1', 60712) - "WebSocket /onebot/v11/ws" [accepted]
11-23 22:38:08 [INFO] nonebot | OneBot V11 | Bot 3134215858 connected
11-23 22:38:08 [INFO] websockets | connection open
11-23 22:38:08 [SUCCESS] nonebot | OneBot V11 3134215858 | [message.group.normal]: Message 367772300 from 867559716@[群:1127741237] "直接搜个小字"
11-23 22:38:08 [DEBUG] nonebot | Checking for matchers in priority 1...
11-23 22:38:08 [DEBUG] nonebot | Checking for matchers in priority 50...
11-23 22:38:22 [INFO] uvicorn | Shutting down
11-23 22:38:22 [WARNING] nonebot | OneBot V11 | WebSocket for Bot 3134215858 closed by peer
11-23 22:38:22 [INFO] websockets | connection closed
11-23 22:38:22 [INFO] uvicorn | Waiting for application shutdown.
11-23 22:38:22 [INFO] uvicorn | Application shutdown complete.
11-23 22:38:22 [INFO] uvicorn | Finished server process [30505]
11-23 22:38:22 [INFO] uvicorn | Stopping reloader process [30501]
